let data = [
    {
        "name" : "Life of Pi",
        "author": "Yann Martel",
        "url": "./images/Life of Pi.png",
        "date": "08/07/22",
        "rating": "8",
        "review": "/life-of-pi.html",
    },
    {
        "name" : "A Man Called Ove",
        "author": "Frederik Backman",
        "url": "./images/A Man Called Ove.png",
        "date": "27/12/21",
        "rating": "7",
        "review": "/a-man-called-ove.html",
    },
    {
        "name" : "The Unlikely Pilgrimage of Harold Fry",
        "author": "Rachel Joyce",
        "url": "./images/The Unlikely Pilgrimage of Harold Fry.png", 
        "date": "21/07/22",
        "rating": "6",
        "review": "/the-unlikely-pilgrimage-of-harold-fry.html",
    },
    {
        "name" : "Neophilia",
        "author": "Lyall Watson",
        "url": "./images/Neophilia.png", 
        "date": "20/08/22",
        "rating": "8",
        "review": "/neophilia.html",
    },
    {
        "name" : "A Thousand Splendid Suns",
        "author": "Khaled Hossein",
        "url": "./images/A Thousand Splendid Suns.png", 
        "date": "30/07/22",
        "rating": "10",
        "review": "/a-thousand-splendid-suns.html",
    },
    {
        "name" : "Animal Farm",
        "author": "George Orwell",
        "url": "./images/Animal Farm.png", 
        "date": "15/08/21",
        "rating": "8",
        "review": "/animal-farm.html",
    },
    {
        "name" : "The Da Vinci Code",
        "author": "Dan Brown",
        "url": "./images/The Da Vinci Code.png", 
        "date": "13/08/22",
        "rating": "9",
        "review": "/the-da-vinci-code.html",
    },
    {
        "name" : "The Pleasure of Finding Things Out",
        "author": "Richard P. Feynman",
        "url": "./images/The Pleasure of Finding Things Out.png", 
        "date": "25/05/22",
        "rating": "9",
        "review": "/the-pleasure-of-finding-things-out.html",
    },
    {
        "name" : "Oscar and the Lady in Pink",
        "author": "Éric-Emmanuel Schmitt",
        "url": "./images/Oscar and the Lady in Pink.png", 
        "date": "24/08/21",
        "rating": "8",
        "review": "/oscar-and-the-lady-in-pink.html",
    },
    {
        "name" : "Skin in the Game",
        "author": "Nassim Nicholas Taleb",
        "url": "./images/Skin in the Game.png", 
        "date": "12/06/20",
        "rating": "6",
        "review": "/skin-in-the-game.html",
    },
    // {
    //     "name" : "Siddhartha",
    //     "author": "Hermann Hesse",
    //     "url": "./images/E-reader.png", 
    //     "date": "12/07/21",
    //     "rating": "6",
    //     "review": "/siddhartha.html",
    // },
    {
        "name" : "Flowers for Algernon",
        "author": "Daniel Keyes",
        "url": "./images/Flowers for Algernon.png",  
        "date": "28/07/21",
        "rating": "10",
        "review": "/flowers-for-algernon.html",
    },
    // {
    //     "name" : "Ten Little Soldiers",
    //     "author": "Agatha Christie",
    //     "url": "./images/E-reader.png",  
    //     "date": "31/07/21",
    //     "rating": "9",
    //     "review": "/ten-little-soldiers.html",
    // },
    {
        "name" : "The Schopenhauer Cure",
        "author": "Irvin D. Yalom",
        "url":  "./images/The Schopenhauer Cure.png",  
        "date": "10/01/22",
        "rating": "7",
        "review": "/the-schopenhauer-cure.html",
    },
    {
        "name" : "The Minds of Billy Milligan",
        "author": "Daniel Keyes",
        "url":  "./images/The Minds of Billy Milligan.png",  
        "date": "11/09/22",
        "rating": "7",
        "review": "/the-minds-of-billy-milligan.html",
    },
    {
        "name" : "The End of Everything",
        "author": "Dr. Katherine (Katie) Mack",
        "url":  "./images/The End of Everything.png",  
        "date": "28/09/22",
        "rating": "8.5",
        "review": "/the-end-of-everything.html",
    },
    {
        "name" : "Perfectly Reasonable Deviations from the Beaten Track",
        "author": "Richard P. and Michelle Feynman",
        "url":  "./images/Perfectly Reasonable Deviations.png",  
        "date": "13/11/22",
        "rating": "8.5",
        "review": "/perfectly-reasonable-deviations.html",
    },
    {
        "name" : "The Amazing Story of the Man Who Cycled from India to Europe for Love",
        "author": "Per J. Andersson, Anna Holmwood (Translation)",
        "url":  "./images/The Amazing Story.png",  
        "date": "28/02/23",
        "rating": "7",
        "review": "/the-amazing-story.html",
    },
    {
        "name" : "The Stranger",
        "author": "Albert Camus",
        "url":  "./images/The Stranger.png",  
        "date": "08/03/23",
        "rating": "6",
        "review": "/the-stranger.html",
    },
    {
        "name" : "Anxious People",
        "author": "Frederik Backman",
        "url":  "./images/Anxious People.png",  
        "date": "21/04/23",
        "rating": "8",
        "review": "/anxious-people.html",
    },
    {
        "name" : "Helgoland",
        "author": "Carlo Rovelli",
        "url":  "./images/Helgoland.png",  
        "date": "29/05/23",
        "rating": "8",
        "review": "/helgoland.html",
    },
    {
        "name" : "Zero - The Biography of a Dangerous Idea",
        "author": "Charles Seife",
        "url":  "./images/Zero.png",  
        "date": "10/06/23",
        "rating": "8",
        "review": "/zero.html",
    },
    {
        "name" : "Papillon",
        "author": "Henri Charrière",
        "url":  "./images/Papillon.png",  
        "date": "05/07/23",
        "rating": "10",
        "review": "/papillon.html",
    },
    {
        "name" : "Dying To Be Me",
        "author": "Anita Moorjani",
        "url":  "./images/Dying To Be Me.png",  
        "date": "31/07/23",
        "rating": "4",
        "review": "/dying-to-be-me.html",
    },
    {
        "name" : "Anaximander",
        "author": "Carlo Rovelli",
        "url":  "./images/Anaximander.png",  
        "date": "19/08/23",
        "rating": "8.5",
        "review": "/anaximander.html",
    },
    {
        "name" : "The Myth of Normal",
        "author": "Gabor Maté",
        "url":  "./images/The Myth of Normal.png",  
        "date": "15/09/23",
        "rating": "8",
        "review": "/the-myth-of-normal.html",
    },
    {
        "name" : "Banco",
        "author": "Henri Charrière",
        "url":  "./images/Banco.png",  
        "date": "22/09/23",
        "rating": "9",
        "review": "/banco.html",
    },
    {
        "name" : "The Shell Collector",
        "author": "Anthony Doerr",
        "url":  "./images/The Shell Collector.png",  
        "date": "05/10/23",
        "rating": "8",
        "review": "/the-shell-collector.html",
    },
    {
        "name" : "A Mathematician's Apology",
        "author": "Godfrey Harold Hardy",
        "url":  "./images/A Mathematician's Apology.png",  
        "date": "08/10/23",
        "rating": "8",
        "review": "/mathematicians-apology.html",
    },
    {
        "name" : "Tribes",
        "author": "Seth Godin",
        "url":  "./images/Tribes.png",  
        "date": "25/10/23",
        "rating": "6.5",
        "review": "/tribes.html",
    },
    {
        "name" : "This Perfect Day",
        "author": "Ira Levin",
        "url":  "./images/This Perfect Day.png",  
        "date": "23/11/23",
        "rating": "8.5",
        "review": "/this-perfect-day.html",
    },
    {
        "name" : "Endurance",
        "author": "Alfred Lansing",
        "url":  "./images/Endurance.png",  
        "date": "02/01/24",
        "rating": "9",
        "review": "/endurance.html",
    },
    {
        "name" : "The Web of Life",
        "author": "John H. Storer",
        "url":  "./images/The Web of Life.png",  
        "date": "21/01/24",
        "rating": "9",
        "review": "/the-web-of-life.html",
    },
    {
        "name" : "OPEN",
        "author": "Andre Agassi",
        "url":  "./images/OPEN.png",  
        "date": "10/02/24",
        "rating": "9",
        "review": "/open.html",
    },
    {
        "name" : "The Solutions Are Already Here",
        "author": "Peter Gelderloos",
        "url":  "./images/Solutions Are Already Here.png",  
        "date": "04/04/24",
        "rating": "6.5",
        "review": "/solutions-are-here.html",
    },
    {
        "name" : "Brave New World",
        "author": "Aldous Huxley",
        "url":  "./images/Brave New World.png",  
        "date": "14/04/24",
        "rating": "7",
        "review": "/brave-new-world.html",
    },
    {
        "name" : "Brave New World Revisited",
        "author": "Aldous Huxley",
        "url":  "./images/Brave New World Revisited.png",  
        "date": "27/04/24",
        "rating": "9",
        "review": "/brave-new-world-revisited.html",
    },
    {
        "name" : "To Kill a Mockingbird",
        "author": "Harper Lee",
        "url":  "./images/To Kill a Mockingbird.png",  
        "date": "13/05/24",
        "rating": "7",
        "review": "/to-kill-a-mockingbird.html",
    },
    {
        "name" : "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "url":  "./images/Thinking Fast and Slow.png",  
        "date": "12/06/24",
        "rating": "10",
        "review": "/thinking-fast-and-slow.html",
    },
    {
        "name" : "Exploration Fawcett: Journey to the Lost City of Z",
        "author": "Percy Fawcett",
        "url":  "./images/Exploration Fawcett.png",  
        "date": "08/07/24",
        "rating": "7.5",
        "review": "/exploration-fawcett.html",
    },
    {
        "name" : "The Cell",
        "author": "Joshua Z. Rappoport",
        "url":  "./images/The Cell.png",  
        "date": "26/07/24",
        "rating": "7",
        "review": "/the-cell.html",
    },
    {
        "name" : "Lord of the Flies",
        "author": "William Golding",
        "url":  "./images/Lord of the Flies.png",  
        "date": "05/08/24",
        "rating": "5",
        "review": "/lord-of-flies.html",
    },
    {
        "name" : "The Book of Laughter and Forgetting",
        "author": "Milan Kundera",
        "url":  "./images/The Book of Laughter and Forgetting.png",  
        "date": "25/08/24",
        "rating": "7.5",
        "review": "/book-of-laughter-and-forgetting.html",
    },
    {
        "name" : "The Blind Watchmaker",
        "author": "Richard Dawkins",
        "url":  "./images/The Blind Watchmaker.png",  
        "date": "27/09/24",
        "rating": "8",
        "review": "/the-blind-watchmaker.html",
    },
    {
        "name" : "The Creative Act",
        "author": "Rick Rubin",
        "url":  "./images/The Creative Act.png",  
        "date": "13/10/24",
        "rating": "5",
        "review": "/the-creative-act.html",
    },
    {
        "name" : "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "url":  "./images/Man's Search for Meaning.png",  
        "date": "25/10/24",
        "rating": "8",
        "review": "/mans-search-for-meaning.html",
    },
    {
        "name" : "Educated",
        "author": "Tara Westover",
        "url":  "./images/Educated.png",  
        "date": "13/11/24",
        "rating": "8",
        "review": "/educated.html",
    },
    {
        "name" : "Entangled Life",
        "author": "Merlin Sheldrake",
        "url":  "./images/Entangled Life.png",  
        "date": "02/12/24",
        "rating": "8",
        "review": "/entangled-life.html",
    },
    {
        "name" : "An Evil Cradling",
        "author": "Brian Keenan",
        "url":  "./images/An Evil Cradling.png",  
        "date": "20/12/24",
        "rating": "7.5",
        "review": "/evil-cradling.html",
    },
    {
        "name" : "The Nature of Nature",
        "author": "Enric Sala",
        "url":  "./images/The Nature of Nature.png",  
        "date": "31/12/24",
        "rating": "10",
        "review": "/nature-of-nature.html",
    },
    {
        "name" : "Love Triangle",
        "author": "Matt Parker",
        "url":  "./images/Love Triangle.png",  
        "date": "22/01/25",
        "rating": "8",
        "review": "/love-triangle.html",
    },
    {
        "name" : "The Man Who Mistook His Wife for a Hat",
        "author": "Oliver Sacks",
        "url":  "./images/The Man Who Mistook His Wife for a Hat.png",  
        "date": "05/02/25",
        "rating": "5",
        "review": "/man-who-mistook-his-wife-for-hat.html",
    },
    {
        "name" : "A Buzz in the Meadow",
        "author": "Dave Goulson",
        "url":  "./images/A Buzz in the Meadow.png", 
        "date": "28/02/25",
        "rating": "9",
        "review": "/buzz-in-the-meadow.html",
    },
    {
        "name" : "Where Crawdads Sing",
        "author": "Delia Owens",
        "url":  "./images/Where Crawdads Sing.png", 
        "date": "11/04/25",
        "rating": "9",
        "review": "/where-crawdads-sing.html",
    },
    {
        "name" : "Midnight in Peking",
        "author": "Paul French",
        "url":  "./images/Midnight in Peking.png", 
        "date": "02/05/25",
        "rating": "10",
        "review": "/midnight-in-peking.html",
    },
    {
        "name" : "How Minds Change",
        "author": "David McRaney",
        "url":  "./images/How Minds Change.png", 
        "date": "18/05/25",
        "rating": "8.5",
        "review": "/how-minds-change.html",
    },
    {
        "name" : "Non Moriamur",
        "author": "Kilian E. Leibundgut",
        "url":  "./images/Non Moriamur.png", 
        "date": "06/03/26",
        "rating": "9",
        "review": "/non-moriamur.html",
    },
    {
        "name" : "Project Hail Mary",
        "author": "Andy Weir",
        "url":  "./images/Project Hail Mary.png", 
        "date": "29/01/26",
        "rating": "8",
        "review": "/project-hail-mary.html",
    },
    {
        "name" : "Everything I Want To Do Is Illegal",
        "author": "Joel Salatin",
        "url":  "./images/Everything I Want To Do Is Illegal.png", 
        "date": "13/11/25",
        "rating": "6",
        "review": "/everything-i-want-to-do-is-illegal.html",
    },
    {
        "name" : "Adventures of a Young Naturalist",
        "author": "David Attenborough",
        "url":  "./images/Adventures Of A Young Naturalist.png", 
        "date": "03/08/25",
        "rating": "7.5",
        "review": "/adventures-of-a-young-naturalist.html",
    },
    {
        "name" : "a universe from nothing",
        "author": "Lawrence M. Krauss",
        "url":  "./images/A Universe From Nothing.png", 
        "date": "06/09/25",
        "rating": "7",
        "review": "/a-universe-from-nothing.html",
    }
]

// data.sort((a, b) => a.author.localeCompare(b.author));